### PR TITLE
fix(gotrue): catch some errors in signOut

### LINKED ISSUE #500: Consider expose _removeSession function
Apple store requires us to provide Account Deletion to users, i tried to implement using Edge Functions, but i can't clear session in user device. If i call `auth.signOut`, i always got `Unhandled Exception: AuthException(message: User not found, statusCode: 404)`. So i suggest to change `_removeSession` to `removeSession` to allows developers call.

### PR DESCRIPTION
**Pull request by Vinzent03**
close #500
I'm catching specifc errors on sign out like in [gotrue-js](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L1059) to prevent errors being thrown in `signOut()`.

### CODE REVIEW

File: packages/gotrue/lib/src/gotrue_client.dart [hunk 1]
```diff
@@ -610,7 +610,17 @@ class GoTrueClient {
...
+        return await admin.signOut(accessToken);
+      } on AuthException catch (error) {
+        // ignore 404s since user might not exist anymore
+        // ignore 401s since an invalid or expired JWT should sign out the current session
+        if (error.statusCode == '401' || error.statusCode == '404') {
+          return;
+        } else {
+          rethrow;
+        }
+      }
```
Comment (dshukertjr) [inline packages/gotrue/lib/src/gotrue_client.dart:623]: Just a minor cleanup

```suggestion
      try {
        await admin.signOut(accessToken);
      } on AuthException catch (error) {
        // ignore 401s since an invalid or expired JWT should sign out the         
        // ignore 404s since user might not exist anymore
current session
        if (error.statusCode != '401' && error.statusCode != '404') {
          rethrow;
        }
      }
```

**Review by dshukertjr — COMMENTED** [review]
Thanks for the quick fix!

File: packages/gotrue/lib/src/gotrue_client.dart (hunk 1 above)
Comment (Vinzent03) [reply packages/gotrue/lib/src/gotrue_client.dart]: Ah great catch!

**Review by dshukertjr — APPROVED** [review]
Looks awesome!
