### PR TITLE
fix: Add newEmail to admin generateLink method

### LINKED ISSUE #893: `GoTrueAdminApi.generateLink()` missing parameter for `newEmail`
**Describe the bug**
The `GoTrueAdminApi.generateLink()` method is missing the parameter for `newEmail` when you are trying to generate a link for an email change. For example:

```dart
  final linkResponse = await supabaseServiceClient.auth.admin.generateLink(
    type: GenerateLinkType.emailChangeNew,
    email: oldEmailAddress,
    newEmail: newEmailAddress, // MISSING
  );
```

The JS API has it: https://supabase.github.io/supabase-js/v2/modules/index.html#GenerateEmailChangeLinkParams

**To Reproduce**
See the code snippet above.

**Expected behavior**
I'm able to generate an email change link.

**Screenshots**
N/A

**Version**
Linux:
```
│   ├── supabase...
├── storage_client 2.0.0
├── supabase 2.0.2
│   ├── functions_client 2.0.0
│   ├── gotrue 2.1.0
│   ├── postgrest 2.0.1
│   ├── realtime_client 2.0.0
│   ├── storage_client...
```

I know I'm a bit behind, but it isn't in the latest gotrue 2.6.0 either.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Vinzent03**
## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

`newEmail` is missing in the admin `generateLink` method

## What is the new behavior?

Added `newEmail` parameter and improved documentation.

## Additional context

close #893

### CODE REVIEW

File: packages/gotrue/lib/src/gotrue_admin_api.dart [hunk 1]
```diff
@@ -121,9 +121,20 @@ class GoTrueAdminApi {
   }
 
   /// Generates links to be sent via email or other.
+  ///
+  /// [password] is  used for [GenerateLinkType.signup]
+  ///
+  /// [newEmail] is used for [GenerateLinkType.emailChangeCurrent]
+  /// and [GenerateLinkType.emailChangeNew]
```
Comment (bdlukaa) [inline packages/gotrue/lib/src/gotrue_admin_api.dart:128]: I think we should do an assertion to ensure `newEmail` is not null if the type is `emailChangeCurrent` or `emailChangeNew`. Same with other properties.

**Review by bdlukaa — APPROVED** [review]
