### PR TITLE
fix(functions_client): use header for response parsing

### LINKED ISSUE #614: FormatException: Unexpected character (at character 1)
**Describe the bug**
If the Edge Function completes its execution due to a timeout, we receive a JSON parsing error. Although, it would be more logical to receive a timeout error

**To Reproduce**
1) Write a function that will run for a very long time.
2) Call this function in a Flutter application.
3) Expect an error.

**Expected behavior**
It would be correct to receive a timeout error

**Screenshots**
Screenshot 2023-09-04 at 11 10 36
Screenshot 2023-09-04 at 11 10 50

**Version (please complete the following information):**
├── supabase_flutter 1.10.14
│   ├── supabase 1.11.1
│   │   ├── functions_client 1.3.2
│   │   ├── gotrue 1.11.2
│   │   ├── postgrest 1.5.0
│   │   ├── realtime_client 1.2.1
│   │   ├── storage_client 1.5.1

### PR DESCRIPTION
**Pull request by Vinzent03**
# Changes
Switches to depend on the response headers on how to parse the response data

That's the way how it's done in `functions-js`  as well. I'm thinking about switching `FunctionResponse.data` to `Object`. That way the user has to verify the response is of their desired type, but I'm unsure this is appreciated.

Close #614

### CODE REVIEW

File: packages/functions_client/lib/src/types.dart [hunk 1]
```diff
@@ -13,19 +9,11 @@ enum HttpMethod {
   patch,
 }
 
-class FunctionInvokeOptions {
```
Comment (Vinzent03) [inline packages/functions_client/lib/src/types.dart:16]: Somehow this isn't even used anymore.

**Comment by dshukertjr** [comment]
Could I ask how this PR fixes https://github.com/supabase/supabase-flutter/issues/614 ?

**Comment by dshukertjr** [comment]
> That way the user has to verify the response is of their desired type, but I'm unsure this is appreciated.

I prefer to keep it dynamic. Most of the case the returned type should be `Map`, and Object is annoying, because it doesn't let you just access values using `[]` directly.

**Comment by Vinzent03** [comment]
The `FormatException` occurs, because you locally specify that the format needs to be a json type, but the server actually sends a text, which can't be parsed to json. So because it only depends on the server how the format actually looks like, I don't think you should be able to specify locally how the result has to look like. And the current functions api is similar to the postgrest api issue, where a method parameter changes the method's return type, which is not common in Dart and I think should be avoided.
But I see now that for the case of a timeout, we should maybe throw errors for non 200 responses. This would also solve this specific issue.

**Review by dshukertjr — APPROVED** [review]
